name: Validate

on:
  - pull_request
  - push

permissions: {}

jobs:
  validate:
    name: Lint & Test
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v6

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          cache: pnpm
          node-version-file: .nvmrc

      - name: Install dependencies
        run: pnpm install

      - name: Test
        run: pnpm test

      - name: Lint
        run: pnpm lint
